### ISSUE TITLE
查询汇率失败

### ISSUE THREAD

**Issue by wdq2347** [tinymins/GoogleExchange.ChromeExt#2]
人在国外还有这个问题吗？
![image](https://user-images.githubusercontent.com/37622363/37709758-51b5268e-2d5f-11e8-95a8-0b5540994fb8.png)

而且设置界面变这样：
![image](https://user-images.githubusercontent.com/37622363/37709785-66652c3c-2d5f-11e8-96e7-9de97916fdb0.png)

**Comment by tinymins** [comment]
我查下 接口又改了感觉

**Comment by wdq2347** [comment]
辛苦了，这个插件我用的最多，速度最快。

**Comment by tinymins** [comment]
https://finance.google.com/finance/converter Google 404了 我有点懵了 你知道现在Google汇率转换地址在哪么

**Comment by 474364707** [comment]
https://cloud.google.com/billing/v1/how-tos/catalog-api?authuser=1&hl=zh-cn

**Comment by 474364707** [comment]
但是隔壁一个Origin比价助手 改了谷歌中国的汇率API接口
https://www.dogfight360.com/blog/764/

**Comment by 474364707** [comment]
http://www.google.cn/finance/stockscreener

**Comment by 474364707** [comment]
http://ip.chinaz.com/www.google.cn/finance/stockscreener

**Comment by wdq2347** [comment]
![image](https://user-images.githubusercontent.com/37622363/37826830-2d6309c8-2ee9-11e8-9cf2-1507d6382de0.png)

**Comment by tinymins** [comment]
搞定了 用了新的架构 等更新就好了_(:з」∠)_

**Comment by 474364707** [comment]
也不知道要等多久...

**Comment by tinymins** [comment]
一般半小时貌似…

**Comment by 474364707** [comment]
炸了用不了....

**Comment by chanvea** [comment]
Connecting www.google.com.hk | Fetching currency from google...

一直连不上 最后网络报错

**Comment by lxyza** [comment]
Connecting www.google.com.hk | Fetching currency from google...

一直连不上 最后网络报错

**Comment by tinymins** [comment]
@lxyza 右键审查元素 看看控制台有没有报错

**Comment by tinymins** [comment]
你们在墙里面没？墙里面不科学上网连不上的_(:з」∠)_

**Comment by lxyza** [comment]
有报错，在墙外，否则我也不能用google mail

2018-03-27 9:58 GMT+08:00 一名宅。 <notifications@github.com>:

**Comment by tinymins** [comment]
@lxyza 报错内容呢(´•灬•｀)

**Comment by lxyza** [comment]
看不到吗


2018-03-27 10:45 GMT+08:00 一名宅。 <notifications@github.com>:

**Comment by tinymins** [comment]
@lxyza 并没有啊 我刷新从上看下来 没有哪里有写报错

**Comment by lxyza** [comment]
是图片，你没刷出来吧
Failed to load
https://www.google.com.hk/async/currency_update?ei=&safe=strict&yv=2&async=source_amount:1,source_currency:null,target_currency:null,chart_width:270,chart_height:94,lang:en,country:,_fmt:jspb:
No 'Access-Control-Allow-Origin' header is present on the requested
resource. Origin 'chrome-extension://mcphipnepdffmgaklcgcogpfbiffmooe' is
therefore not allowed access.
index.html#/popup:1 Failed to load
https://www.google.com.hk/search?q=usd+to+cny&gws_rd=cr: No
'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'chrome-extension://mcphipnepdffmgaklcgcogpfbiffmooe' is therefore
not allowed access.

2018-03-27 11:05 GMT+08:00 一名宅。 <notifications@github.com>:

**Comment by tinymins** [comment]
好了 提交了更新 一小时之后就该好了

**Comment by tinymins** [comment]
试了下 可以更新了

**Comment by lxyza** [comment]
我这里还是现实错误，晕了。

2018-03-27 12:01 GMT+08:00 一名宅。 <notifications@github.com>:

**Comment by lxyza** [comment]
好了，可以更新了，界面换了？


2018-03-27 13:19 GMT+08:00 Fei Liu <lflxyz008@gmail.com>:

**Comment by tinymins** [comment]
组件化了 总体没变稍微改了下实现方式 后面有功能想加的话 现在很容易加了
