### ISSUE TITLE
下拉选项显示无数据。。。

### ISSUE THREAD

**Issue by atyanta-z** [tinymins/GoogleExchange.ChromeExt#3]
好像一切都没有数据..不知道会不会跟梯子有关？
麻烦大佬了。。Orz
Linux openSUSE 4.4.120-45-default

![spectacle j24308](https://user-images.githubusercontent.com/38174812/38463812-55b2e364-3b35-11e8-9547-1ab174c9fb53.png)

**Comment by tinymins** [comment]
。才看到 还是没数据么

**Comment by atyanta-z** [comment]
已经ok了，非常感谢！
