### ISSUE TITLE
请求失败 400  not errmsg

### ISSUE THREAD

**Issue by 474364707** [tinymins/GoogleExchange.ChromeExt#5]
请求失败 400

not errmsg

**Comment by tinymins** [comment]
Google 又改了API 我找时间修一下orz

**Comment by 474364707** [comment]
周末少喝少玩少piao 就有时间修了...

**Comment by 474364707** [comment]
....更新一下 过年了..

**Comment by 474364707** [comment]
https://www.google.com.hk/search?q=USD+to+CNY

**Comment by tinymins** [comment]
修…了… 上班狗太惨… 当年写着个的时候还是个无所事事的学生狗…

**Comment by tinymins** [comment]
![image](https://user-images.githubusercontent.com/1808990/54930097-9eff7d80-4f51-11e9-8c37-366bbc7d0096.png)
顺便增加了交换按钮（

**Comment by tinymins** [comment]
https://github.com/tinymins/GoogleExchange.ChromeExt/commit/006183da0d89b844128e7fb5847348ac2502304f
